### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by C-MacD** [FRCTeam3044/Team3044-2019#16]
- [x] Climber arm encoder removed, not yet from code.

- [x] Shoulder PID sometimes starts when robot enabled, should only start after button press.  Possibly caused based on where and when the mode is set.  (Fixed #15)

- [x] Wrist encoder reset does not work.  (Fixed #15)

- [x] Add manual control of PID so drivers can make fine-tuning adjustments. (#17)
  - [x] Now add it to the wrist. (#17)

- [x] Camera is super laggy. An ok fix described in #20.

- [x] Cargo PID positions labeled as hatches.

- [ ] We could use some auto code, even just basic stuff.  Nav-x would help.  Project for Detroit?

  - [ ] We need a vision system, line following, Nav-x angle alignment, or similar.

- [ ] Failure mode isn't really a thing because we lack automation.

- [x] No stall voltage limiting.  Now done-ish.

- [ ] Clean up code.  Find better homes for things.  Comment things.  Use constants.

- [x] Make arm PID work when in climb mode. (#17)

- [ ] Limit the value of the setpoints so manual control doesn't send them into impossible ranges.

We lack positions for:

- [x] Cargo in the rocket level 1

- [x] Cargo in the rocket level 2

- [ ] Hatches level 2

- [ ] Backwards cargo scoring (should we have it?)

List source primarily from #13
